import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Container from "@/components/ui/Container";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
       lang="en" >
      <body className={poppins.className}>
          <Container>
            {children}
          </Container>
      </body>
    </html>
  );
}
